### ISSUE TITLE
PyPI version does not match tags, setup.py

### ISSUE THREAD

**Issue by fghaas** [hastexo/olx-utils#23]
This PyPI released version of this package is 0.1.0, but `setup.py` in `master` still says 0.9.0, and we're missing a `v0.1.0` tag.

To get things fixed cleanly, we should probably tag a 0.1.1 release and push that.

**Comment by arbrandes** [comment]
Fixed via e86e36, and also [on PyPI](https://pypi.org/project/olx-utils/0.1.1/)

**Comment by fghaas** [comment]
Thanks!
